# Generated by Django 4.0.3 on 2022-04-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('distance', models.IntegerField()),
            ],
        ),
    ]
